$axure.loadCurrentPage({
  "url":"流程图.html",
  "generationDate":new Date(1660126800663.77),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"f2259295509a40389b4169842ac88ce4",
    "type":"Axure:Page",
    "name":"流程图",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e465a1cfcb6d4e72ba714ef4f46a73a6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":30},
            "size":{
              "width":1558,
              "height":3032}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a851c40b045647b2834c3744a1180389",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":30},
                "size":{
                  "width":1558,
                  "height":3032}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/流程图/u0.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e465a1cfcb6d4e72ba714ef4f46a73a6":{
      "scriptId":"u0"},
    "a851c40b045647b2834c3744a1180389":{
      "scriptId":"u1"}}});