$axure.loadCurrentPage({
  "url":"主页.html",
  "generationDate":new Date(1659754425868.92),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6c39090b765d415299a9a52f0e4a5b4a",
    "type":"Axure:Page",
    "name":"主页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"4c3aed55766d4f51bbe4984b832e16ad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":10},
            "size":{
              "width":621,
              "height":1170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ff49cbdf55c7459a8a143b6361adf8ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":10},
                "size":{
                  "width":621,
                  "height":1170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u0.jpg"}},
{
          "id":"b541050744064d8b89e32e1d50971b6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":850,
              "y":612},
            "size":{
              "width":337,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1d6e34ba9bd4e71a400a50d1f0cd2c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":850,
                  "y":612},
                "size":{
                  "width":337,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"dda2b065b9c4407f9a58e882b8d6418b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":1190},
            "size":{
              "width":621,
              "height":1104}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a01f0baa70047ff8d2b5e101a2af0ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":1190},
                "size":{
                  "width":621,
                  "height":1104}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u4.jpg"}},
{
          "id":"c32427ee6d384d7b9042fa9ec1cf1244",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":801,
              "y":2304},
            "size":{
              "width":621,
              "height":1104}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"056c62b64b364f6387f5841b6b35a9c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":801,
                  "y":2304},
                "size":{
                  "width":621,
                  "height":1104}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u6.jpg"}},
{
          "id":"818b24b6715e490ca5561a3399d5d33a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":2304},
            "size":{
              "width":621,
              "height":1104}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a1a4f9e3298e40c88859f2030851eace",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":2304},
                "size":{
                  "width":621,
                  "height":1104}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u8.jpg"}},
{
          "id":"cdb39d73a33342f3bad5d023708c150e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1432,
              "y":2304},
            "size":{
              "width":621,
              "height":1104}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe6aa6cc9577428f93c561c89286e9b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1432,
                  "y":2304},
                "size":{
                  "width":621,
                  "height":1104}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u10.jpg"}},
{
          "id":"caadf89c15a74b0ab48acd6ce8a1788b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2070,
              "y":2304},
            "size":{
              "width":621,
              "height":1104}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25394f2a2e4546f39fff09435d8d6920",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2070,
                  "y":2304},
                "size":{
                  "width":621,
                  "height":1104}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u12.jpg"}},
{
          "id":"1faa46d5c3184a68b5427b67bb2ac422",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":2710,
              "y":2304},
            "size":{
              "width":621,
              "height":1104}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7faf5d6876fe4461b72c35003dd9cce4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":2710,
                  "y":2304},
                "size":{
                  "width":621,
                  "height":1104}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u14.jpg"}},
{
          "id":"dd18a8efed7849b9bc411805ff152665",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":3418},
            "size":{
              "width":621,
              "height":1104}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c7b7fd8972da43c893b4d281dafb5614",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":3418},
                "size":{
                  "width":621,
                  "height":1104}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u16.jpg"}},
{
          "id":"e13ae6cf94444800ac27a35a8e5ec591",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":4532},
            "size":{
              "width":621,
              "height":1104}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7b7e15d805f042a58d1e7d0d81942018",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":4532},
                "size":{
                  "width":621,
                  "height":1104}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u18.jpg"}},
{
          "id":"3556ee8be98141b7a9b59097de411b49",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":5646},
            "size":{
              "width":610,
              "height":695}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9efba1719dcd47318106b1b78bf072cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":5646},
                "size":{
                  "width":610,
                  "height":695}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u20.jpg"}},
{
          "id":"61b6f7fa0e324ef0b490385b62a3deb5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1432,
              "y":3418},
            "size":{
              "width":621,
              "height":1104}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"55cf77b7a8244c25b0bda874ebbd135e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1432,
                  "y":3418},
                "size":{
                  "width":621,
                  "height":1104}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u22.jpg"}},
{
          "id":"588fc34a1eb242f7995a603b8481a573",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1432,
              "y":4546},
            "size":{
              "width":621,
              "height":1104}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac8ec6dbb6de4eaaaea0b48feca94056",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1432,
                  "y":4546},
                "size":{
                  "width":621,
                  "height":1104}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/主页/u24.jpg"}},
{
          "id":"a097abea527045ae8ebf1e3dc2215cbb",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":540},
            "size":{
              "width":550,
              "height":490}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 文章",
                      "target":{
                        "targetType":"page",
                        "url":"文章.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"8c4d777421a3476cb821464b0208bcad",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":1500},
            "size":{
              "width":500,
              "height":110}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 企业介绍等",
                      "target":{
                        "targetType":"page",
                        "url":"企业介绍等.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"4f4643aa4df741aab97a293e10cb7ad7",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":240,
              "y":1360},
            "size":{
              "width":500,
              "height":90}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 浏览所有产品",
                      "target":{
                        "targetType":"page",
                        "url":"浏览所有产品.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"cf2e5a14142946b18b5308628554be9c",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":2420},
            "size":{
              "width":590,
              "height":650}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 企业介绍等",
                      "target":{
                        "targetType":"page",
                        "url":"企业介绍等.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"eb53aa1761904a19918b1946af9c55fa",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":820,
              "y":3180},
            "size":{
              "width":580,
              "height":70}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 浏览所有产品",
                      "target":{
                        "targetType":"page",
                        "url":"浏览所有产品.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"891af6d864424bc0a7f0d6a10e38b32f",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":2500},
            "size":{
              "width":570,
              "height":800}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 产品介绍",
                      "target":{
                        "targetType":"page",
                        "url":"产品介绍.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "4c3aed55766d4f51bbe4984b832e16ad":{
      "scriptId":"u0"},
    "ff49cbdf55c7459a8a143b6361adf8ce":{
      "scriptId":"u1"},
    "b541050744064d8b89e32e1d50971b6a":{
      "scriptId":"u2"},
    "a1d6e34ba9bd4e71a400a50d1f0cd2c0":{
      "scriptId":"u3"},
    "dda2b065b9c4407f9a58e882b8d6418b":{
      "scriptId":"u4"},
    "3a01f0baa70047ff8d2b5e101a2af0ba":{
      "scriptId":"u5"},
    "c32427ee6d384d7b9042fa9ec1cf1244":{
      "scriptId":"u6"},
    "056c62b64b364f6387f5841b6b35a9c7":{
      "scriptId":"u7"},
    "818b24b6715e490ca5561a3399d5d33a":{
      "scriptId":"u8"},
    "a1a4f9e3298e40c88859f2030851eace":{
      "scriptId":"u9"},
    "cdb39d73a33342f3bad5d023708c150e":{
      "scriptId":"u10"},
    "fe6aa6cc9577428f93c561c89286e9b6":{
      "scriptId":"u11"},
    "caadf89c15a74b0ab48acd6ce8a1788b":{
      "scriptId":"u12"},
    "25394f2a2e4546f39fff09435d8d6920":{
      "scriptId":"u13"},
    "1faa46d5c3184a68b5427b67bb2ac422":{
      "scriptId":"u14"},
    "7faf5d6876fe4461b72c35003dd9cce4":{
      "scriptId":"u15"},
    "dd18a8efed7849b9bc411805ff152665":{
      "scriptId":"u16"},
    "c7b7fd8972da43c893b4d281dafb5614":{
      "scriptId":"u17"},
    "e13ae6cf94444800ac27a35a8e5ec591":{
      "scriptId":"u18"},
    "7b7e15d805f042a58d1e7d0d81942018":{
      "scriptId":"u19"},
    "3556ee8be98141b7a9b59097de411b49":{
      "scriptId":"u20"},
    "9efba1719dcd47318106b1b78bf072cf":{
      "scriptId":"u21"},
    "61b6f7fa0e324ef0b490385b62a3deb5":{
      "scriptId":"u22"},
    "55cf77b7a8244c25b0bda874ebbd135e":{
      "scriptId":"u23"},
    "588fc34a1eb242f7995a603b8481a573":{
      "scriptId":"u24"},
    "ac8ec6dbb6de4eaaaea0b48feca94056":{
      "scriptId":"u25"},
    "a097abea527045ae8ebf1e3dc2215cbb":{
      "scriptId":"u26"},
    "8c4d777421a3476cb821464b0208bcad":{
      "scriptId":"u27"},
    "4f4643aa4df741aab97a293e10cb7ad7":{
      "scriptId":"u28"},
    "cf2e5a14142946b18b5308628554be9c":{
      "scriptId":"u29"},
    "eb53aa1761904a19918b1946af9c55fa":{
      "scriptId":"u30"},
    "891af6d864424bc0a7f0d6a10e38b32f":{
      "scriptId":"u31"}}});