$axure.loadCurrentPage({
  "url":"消息.html",
  "generationDate":new Date(1659768281833.99),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"679522dd820a4edfa384a1f22c937b8f",
    "type":"Axure:Page",
    "name":"消息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d46e6cd613dc4c1cacad52e84c4fed19",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":9.99998474121094},
            "size":{
              "width":621,
              "height":1170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c8fae738af14b6da0bc8500195a1f6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":9.99998474121094},
                "size":{
                  "width":621,
                  "height":1170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/消息/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "d46e6cd613dc4c1cacad52e84c4fed19":{
      "scriptId":"u0"},
    "8c8fae738af14b6da0bc8500195a1f6b":{
      "scriptId":"u1"}}});