$axure.loadCurrentPage({
  "url":"完善我的名片.html",
  "generationDate":new Date(1659752328185.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7411e6eec0d949d29ad0b293447983fe",
    "type":"Axure:Page",
    "name":"完善我的名片",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dadd9a1cab62439d80949e0d3164b4e3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":0},
            "size":{
              "width":621,
              "height":1170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f682b443bc94ab381097f978a6b3a81",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":0},
                "size":{
                  "width":621,
                  "height":1170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/完善我的名片/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "dadd9a1cab62439d80949e0d3164b4e3":{
      "scriptId":"u0"},
    "7f682b443bc94ab381097f978a6b3a81":{
      "scriptId":"u1"}}});