$axure.loadCurrentPage({
  "url":"后端查询用户风险测评结果.html",
  "generationDate":new Date(1660118457738.45),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ee43cec9f7da46d0935737e061f90d01",
    "type":"Axure:Page",
    "name":"后端查询用户风险测评结果",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ad57daf2109749d18f67cd4d8f16ff60",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":120,
              "y":47},
            "size":{
              "width":200,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8d52cbda40a484ca0e492f59e80aee8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":120,
                  "y":47},
                "size":{
                  "width":200,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f86649375d9d4fe3975be04e08b81e62",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":125},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"f405eaa78de24af6b886d5471a99e5e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":137,
              "y":130},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23295966a31849f0a8d2d074904ddae0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":137,
                  "y":130},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1237ed0f09b7483bbf03fd2a1fc5762f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":125},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"25bc97112d15474f8ce9c03feb529be4",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":190},
            "size":{
              "width":300,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e36da83eff7446c92bd598a519af36f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6a4976dd90cf490fae31fc4373e4fe86",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看基金净值/u9.png"}},
{
              "id":"5a2fc6f7c3f34c47ba39c12d58b47b69",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2b0c5085c14f49d3a767c11d77c25b85",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看基金净值/u9.png"}},
{
              "id":"27f8151e1c0d426592c892bef33ef428",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"9fb1d12b48ea4ab8bcb9feb0249ca3b8",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看基金净值/u21.png"}},
{
              "id":"182010eebd9e4f36be22c325710bf48f",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"63216fc049444151adff59eb04a329c1",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看基金净值/u9.png"}},
{
              "id":"c3ac2d4141f24043bbba1d62aa42c0be",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a706b8acc5904603ba5df2c2d69c2ccd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看基金净值/u9.png"}},
{
              "id":"41730f582170473ba8eede5f0a6d6a47",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"386b022a91814d9fa9e0373421bab854",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看基金净值/u21.png"}},
{
              "id":"e9a4fbbfbc3c40e298aa42315547764e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"560491bc70164abe81af12ecc176fcf9",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看基金净值/u13.png"}},
{
              "id":"5abd7f3eb8d243a9b77eb62c99050622",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"2a3aa351d60f42c09850a60d06afe238",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看基金净值/u13.png"}},
{
              "id":"b18559ab6ed04fa4b495dbf3a8b295ad",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"1c436e9b6fd34dcf860831de6d7ad6d2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看基金净值/u25.png"}}]}]}},
  "masters":{
},
  "objectPaths":{
    "ad57daf2109749d18f67cd4d8f16ff60":{
      "scriptId":"u0"},
    "d8d52cbda40a484ca0e492f59e80aee8":{
      "scriptId":"u1"},
    "f86649375d9d4fe3975be04e08b81e62":{
      "scriptId":"u2"},
    "f405eaa78de24af6b886d5471a99e5e8":{
      "scriptId":"u3"},
    "23295966a31849f0a8d2d074904ddae0":{
      "scriptId":"u4"},
    "1237ed0f09b7483bbf03fd2a1fc5762f":{
      "scriptId":"u5"},
    "25bc97112d15474f8ce9c03feb529be4":{
      "scriptId":"u6"},
    "0e36da83eff7446c92bd598a519af36f":{
      "scriptId":"u7"},
    "6a4976dd90cf490fae31fc4373e4fe86":{
      "scriptId":"u8"},
    "182010eebd9e4f36be22c325710bf48f":{
      "scriptId":"u9"},
    "63216fc049444151adff59eb04a329c1":{
      "scriptId":"u10"},
    "e9a4fbbfbc3c40e298aa42315547764e":{
      "scriptId":"u11"},
    "560491bc70164abe81af12ecc176fcf9":{
      "scriptId":"u12"},
    "5a2fc6f7c3f34c47ba39c12d58b47b69":{
      "scriptId":"u13"},
    "2b0c5085c14f49d3a767c11d77c25b85":{
      "scriptId":"u14"},
    "c3ac2d4141f24043bbba1d62aa42c0be":{
      "scriptId":"u15"},
    "a706b8acc5904603ba5df2c2d69c2ccd":{
      "scriptId":"u16"},
    "5abd7f3eb8d243a9b77eb62c99050622":{
      "scriptId":"u17"},
    "2a3aa351d60f42c09850a60d06afe238":{
      "scriptId":"u18"},
    "27f8151e1c0d426592c892bef33ef428":{
      "scriptId":"u19"},
    "9fb1d12b48ea4ab8bcb9feb0249ca3b8":{
      "scriptId":"u20"},
    "41730f582170473ba8eede5f0a6d6a47":{
      "scriptId":"u21"},
    "386b022a91814d9fa9e0373421bab854":{
      "scriptId":"u22"},
    "b18559ab6ed04fa4b495dbf3a8b295ad":{
      "scriptId":"u23"},
    "1c436e9b6fd34dcf860831de6d7ad6d2":{
      "scriptId":"u24"}}});