$axure.loadCurrentPage({
  "url":"连线成功.html",
  "generationDate":new Date(1659755611913.48),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"34a2ba3d5e9044749901089583d95791",
    "type":"Axure:Page",
    "name":"连线成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a7ab0d001dd441168f7ef6dc7989eeed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":10},
            "size":{
              "width":626,
              "height":1174}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aee461c736db49c788cb09f9b1330fed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":10},
                "size":{
                  "width":626,
                  "height":1174}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/连线成功/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "a7ab0d001dd441168f7ef6dc7989eeed":{
      "scriptId":"u0"},
    "aee461c736db49c788cb09f9b1330fed":{
      "scriptId":"u1"}}});