$axure.loadCurrentPage({
  "url":"系统消息.html",
  "generationDate":new Date(1659768281898.49),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4f9ac968bbaf47ddb876f2c7008a15f9",
    "type":"Axure:Page",
    "name":"系统消息",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c25e81cc30a74f90a3c9df52401dce10",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":20},
            "size":{
              "width":621,
              "height":1170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e11d0a63c5f4a5d9d7a8c340539afe0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":169,
                  "y":20},
                "size":{
                  "width":621,
                  "height":1170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/系统消息/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "c25e81cc30a74f90a3c9df52401dce10":{
      "scriptId":"u0"},
    "3e11d0a63c5f4a5d9d7a8c340539afe0":{
      "scriptId":"u1"}}});