$axure.loadCurrentPage({
  "url":"业务咨询、客服列表.html",
  "generationDate":new Date(1659755611894.17),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a811c06bffdd4270be7ae4b1c738e09a",
    "type":"Axure:Page",
    "name":"业务咨询、客服列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"44786fb59e564ac08dfa3fc6a29456de",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":110,
              "y":10},
            "size":{
              "width":621,
              "height":1170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ad4bbbae048d4f669360ec2eeff0caf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":110,
                  "y":10},
                "size":{
                  "width":621,
                  "height":1170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/业务咨询、客服列表/u0.jpg"}},
{
          "id":"4d1bae3c94c14951871c8ecb4cb54a7e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":108,
              "y":1200},
            "size":{
              "width":623,
              "height":580}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4e80bf6a1ee49fbaf2aeba18ac674b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":108,
                  "y":1200},
                "size":{
                  "width":623,
                  "height":580}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/业务咨询、客服列表/u2.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "44786fb59e564ac08dfa3fc6a29456de":{
      "scriptId":"u0"},
    "ad4bbbae048d4f669360ec2eeff0caf1":{
      "scriptId":"u1"},
    "4d1bae3c94c14951871c8ecb4cb54a7e":{
      "scriptId":"u2"},
    "b4e80bf6a1ee49fbaf2aeba18ac674b9":{
      "scriptId":"u3"}}});