$axure.loadCurrentPage({
  "url":"取消收藏.html",
  "generationDate":new Date(1660103880250.54),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9fb3c179b6574f6b97f590bd090989be",
    "type":"Axure:Page",
    "name":"取消收藏",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a75d8753ac124e1e8a77ed0f51fceaad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":134,
              "y":10},
            "size":{
              "width":626,
              "height":1174}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca1258eefdc343819e5a5bf5a4a9ab7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":134,
                  "y":10},
                "size":{
                  "width":626,
                  "height":1174}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/取消收藏/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "a75d8753ac124e1e8a77ed0f51fceaad":{
      "scriptId":"u0"},
    "ca1258eefdc343819e5a5bf5a4a9ab7a":{
      "scriptId":"u1"}}});