$axure.loadCurrentPage({
  "url":"新需求.html",
  "generationDate":new Date(1659921932326.55),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1ab12eae05124e0b9fa1deda9cd5454f",
    "type":"Axure:Page",
    "name":"新需求",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"766751f08e9b4026a04be4e3d2b7b74a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":194,
              "y":16},
            "size":{
              "width":616,
              "height":414},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6407c88e79f14245801c77f4e2fb69fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":194,
                  "y":16},
                "size":{
                  "width":616,
                  "height":414},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新需求/u0.png"}},
{
          "id":"680e6ebeba2c48f79a08cfad6157fae5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":194,
              "y":630},
            "size":{
              "width":616,
              "height":677},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2e00b899f2e4cbba880f1b4dd878b0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":194,
                  "y":630},
                "size":{
                  "width":616,
                  "height":677},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新需求/u2.png"}},
{
          "id":"f5d70ba9ca1340cbae9066eca1a4b66a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":194,
              "y":430},
            "size":{
              "width":616,
              "height":206},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09eca2942dfd4dbdb18043f34bd57186",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":194,
                  "y":430},
                "size":{
                  "width":616,
                  "height":206},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新需求/u4.png"}},
{
          "id":"92095314a83641c58cf186804591f674",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":440},
            "size":{
              "width":130,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a9a0e04f16f4f9da6c172ebb8f77529",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":440},
                "size":{
                  "width":130,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新需求/u6.png"}},
{
          "id":"79e105a3f8804f37acc35d011b53f409",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":451},
            "size":{
              "width":129,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cef5501262346158c731fb8663827da",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":451},
                "size":{
                  "width":129,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb87e6bf240c41fea33f9eb0ab4107d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":240,
              "y":570},
            "size":{
              "width":110,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b79523a98dbf4594a5eb9cec5a9b79cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":240,
                  "y":570},
                "size":{
                  "width":110,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新需求/u10.png"}},
{
          "id":"39a88de7a38e43fcb984ae942493e590",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":380,
              "y":570},
            "size":{
              "width":110,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6ef4674cec534a81ba969c9abd910210",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":380,
                  "y":570},
                "size":{
                  "width":110,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新需求/u10.png"}},
{
          "id":"d40dd4da2aa146ec86eaa16a18e8f14f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":520,
              "y":570},
            "size":{
              "width":130,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d42b4416329c4112bfadbf0d0e4e5a11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":520,
                  "y":570},
                "size":{
                  "width":130,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新需求/u14.png"}},
{
          "id":"119d42e0e5f64824b3a8007ca9e83c8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":670,
              "y":570},
            "size":{
              "width":110,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecb3bf54650c4eab95eb878f050f1085",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":670,
                  "y":570},
                "size":{
                  "width":110,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/新需求/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "766751f08e9b4026a04be4e3d2b7b74a":{
      "scriptId":"u0"},
    "6407c88e79f14245801c77f4e2fb69fe":{
      "scriptId":"u1"},
    "680e6ebeba2c48f79a08cfad6157fae5":{
      "scriptId":"u2"},
    "f2e00b899f2e4cbba880f1b4dd878b0d":{
      "scriptId":"u3"},
    "f5d70ba9ca1340cbae9066eca1a4b66a":{
      "scriptId":"u4"},
    "09eca2942dfd4dbdb18043f34bd57186":{
      "scriptId":"u5"},
    "92095314a83641c58cf186804591f674":{
      "scriptId":"u6"},
    "4a9a0e04f16f4f9da6c172ebb8f77529":{
      "scriptId":"u7"},
    "79e105a3f8804f37acc35d011b53f409":{
      "scriptId":"u8"},
    "4cef5501262346158c731fb8663827da":{
      "scriptId":"u9"},
    "bb87e6bf240c41fea33f9eb0ab4107d0":{
      "scriptId":"u10"},
    "b79523a98dbf4594a5eb9cec5a9b79cb":{
      "scriptId":"u11"},
    "39a88de7a38e43fcb984ae942493e590":{
      "scriptId":"u12"},
    "6ef4674cec534a81ba969c9abd910210":{
      "scriptId":"u13"},
    "d40dd4da2aa146ec86eaa16a18e8f14f":{
      "scriptId":"u14"},
    "d42b4416329c4112bfadbf0d0e4e5a11":{
      "scriptId":"u15"},
    "119d42e0e5f64824b3a8007ca9e83c8c":{
      "scriptId":"u16"},
    "ecb3bf54650c4eab95eb878f050f1085":{
      "scriptId":"u17"}}});