$axure.loadCurrentPage({
  "url":"留言成功.html",
  "generationDate":new Date(1659752328016.1),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"be32ac4c05ed4077b7f32da52ba38056",
    "type":"Axure:Page",
    "name":"留言成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d9cdbd6a1af641eda362c745437b5a77",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":172,
              "y":20},
            "size":{
              "width":628,
              "height":1180}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0ee0779efe924c3d99908bb799e3a01c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":172,
                  "y":20},
                "size":{
                  "width":628,
                  "height":1180}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/留言成功/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "d9cdbd6a1af641eda362c745437b5a77":{
      "scriptId":"u0"},
    "0ee0779efe924c3d99908bb799e3a01c":{
      "scriptId":"u1"}}});