$axure.loadCurrentPage({
  "url":"我的名片.html",
  "generationDate":new Date(1659921932218.23),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7f289caa317e45a3a6fcd280b2a5ccd4",
    "type":"Axure:Page",
    "name":"我的名片",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"6694d4e5091e43429b8a85c77b516744",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":20},
            "size":{
              "width":621,
              "height":1170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e4db039b0e54fcf8f9a68e32fe0a710",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":169,
                  "y":20},
                "size":{
                  "width":621,
                  "height":1170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的名片/u0.jpg"}}]}},
  "masters":{
},
  "objectPaths":{
    "6694d4e5091e43429b8a85c77b516744":{
      "scriptId":"u0"},
    "9e4db039b0e54fcf8f9a68e32fe0a710":{
      "scriptId":"u1"}}});