$axure.loadCurrentPage({
  "url":"企业介绍等.html",
  "generationDate":new Date(1660103880160.44),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6c12871592514a46a23b0f9fce371b9a",
    "type":"Axure:Page",
    "name":"企业介绍等",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"918a15a6eb884634b1f72bcfff12dbda",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":110},
            "size":{
              "width":621,
              "height":1170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"28b643903b3e4be7b3c481f7114649d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":110},
                "size":{
                  "width":621,
                  "height":1170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/企业介绍等/u0.jpg"}},
{
          "id":"d294c5caf947458889f0c26d811d1c90",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":50},
            "size":{
              "width":289,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24847f088bd44756ba47fd64d00b72af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":156,
                  "y":50},
                "size":{
                  "width":289,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a09dcb78aa6440c6bfb764862b1c0201",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":750,
              "y":110},
            "size":{
              "width":621,
              "height":1170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f13399fbb58341b8bd495f25da2e3f68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":750,
                  "y":110},
                "size":{
                  "width":621,
                  "height":1170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/企业介绍等/u4.jpg"}},
{
          "id":"9b72050a5c304d3cb00b49ad60e042cd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":739,
              "y":1290},
            "size":{
              "width":621,
              "height":1170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe8e516913b74f95aae857442a402f27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":739,
                  "y":1290},
                "size":{
                  "width":621,
                  "height":1170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/企业介绍等/u4.jpg"}},
{
          "id":"8de15389cbfc45999e2e3ffa503458d8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":1490,
              "y":110},
            "size":{
              "width":621,
              "height":1170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b7d1fae89ab54c54a0416cbf15d1757a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1490,
                  "y":110},
                "size":{
                  "width":621,
                  "height":1170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/企业介绍等/u8.jpg"}},
{
          "id":"d35a853d63124d7287e4a7a5a4f978f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":1580,
              "y":40},
            "size":{
              "width":129,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a48bbdae4e648e7bba10e95c394ad8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":1580,
                  "y":40},
                "size":{
                  "width":129,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "918a15a6eb884634b1f72bcfff12dbda":{
      "scriptId":"u0"},
    "28b643903b3e4be7b3c481f7114649d6":{
      "scriptId":"u1"},
    "d294c5caf947458889f0c26d811d1c90":{
      "scriptId":"u2"},
    "24847f088bd44756ba47fd64d00b72af":{
      "scriptId":"u3"},
    "a09dcb78aa6440c6bfb764862b1c0201":{
      "scriptId":"u4"},
    "f13399fbb58341b8bd495f25da2e3f68":{
      "scriptId":"u5"},
    "9b72050a5c304d3cb00b49ad60e042cd":{
      "scriptId":"u6"},
    "fe8e516913b74f95aae857442a402f27":{
      "scriptId":"u7"},
    "8de15389cbfc45999e2e3ffa503458d8":{
      "scriptId":"u8"},
    "b7d1fae89ab54c54a0416cbf15d1757a":{
      "scriptId":"u9"},
    "d35a853d63124d7287e4a7a5a4f978f1":{
      "scriptId":"u10"},
    "3a48bbdae4e648e7bba10e95c394ad8f":{
      "scriptId":"u11"}}});