$axure.loadCurrentPage({
  "url":"查看基金净值.html",
  "generationDate":new Date(1660103880653.43),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"38ec3151bc064d66862880a2093224e2",
    "type":"Axure:Page",
    "name":"查看基金净值",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8647ad65ff0e409ea9d43ed9e6fbd1e4",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":0},
            "size":{
              "width":620,
              "height":760}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"143ebd4e802e475bafd5f7c7e43d064b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":0},
                "size":{
                  "width":620,
                  "height":760}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看基金净值/u0.png"}},
{
          "id":"33b7374af81b4f2c95c4c41e26135e90",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":46},
            "size":{
              "width":363,
              "height":261}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f9e24f8c413248448af9fbb1ffb53b64",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":130,
                  "y":46},
                "size":{
                  "width":363,
                  "height":261}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看基金净值/u2.jpg"}},
{
          "id":"3674615cae054fbfb721242bd78e0412",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":41,
              "y":353},
            "size":{
              "width":569,
              "height":289}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7676c4ab66044f72ad2a3c6849841c1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":41,
                  "y":353},
                "size":{
                  "width":569,
                  "height":289}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/查看基金净值/u4.jpg"}},
{
          "id":"cbf44fdaa7cf47dc97f3b3cbbb036983",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":636,
              "y":172},
            "size":{
              "width":659,
              "height":114}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0bc4bf5529ff47eaa66c383ad4fa5312",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":636,
                  "y":172},
                "size":{
                  "width":659,
                  "height":114}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ee008f00753340b59e53827fe7a84d46",
          "label":"",
          "type":"table",
          "styleType":"table",
          "visible":true,
          "style":{
            "location":{
              "x":720,
              "y":248},
            "size":{
              "width":300,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e51b8eeccf834a76b918ab5142809515",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"c17ca8bdbbd04ebbae7c65c9f140574d",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看基金净值/u9.png"}},
{
              "id":"e1a46afc28b144b681f79dc50448dcc2",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"de154c332c5a4ce08711ed78f79bc259",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看基金净值/u9.png"}},
{
              "id":"3ffe1c2ecdaa44dd99815a6984ef7de3",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":0,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"4e7f393ece6241ce918a98bf7a3f9e36",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":0,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看基金净值/u21.png"}},
{
              "id":"ddf01e81d5c14ea78e7b8e283dd73a6e",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"dfdf9cf8ccf0427ea1c4e4b8db276cbf",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看基金净值/u9.png"}},
{
              "id":"4e0701002e4948858c4431ca866e7642",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"e1d5d8fffdb5402d9d2eb7845d51c19c",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看基金净值/u9.png"}},
{
              "id":"0dc8247259f847ca8d8be764ab4b7427",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":100,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"8ba3ca9545dc4733ba23e9e2fc0dcb6b",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":100,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看基金净值/u21.png"}},
{
              "id":"9758c331a4d74006bd2b6e3cff60e2fb",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":0},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6952e97a4a704acda7b5c33dcb7921b2",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":0},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看基金净值/u13.png"}},
{
              "id":"f3ed505831d24ab090cd959ceca37f9b",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":30},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"89c7ed01634a44e093ff8a448d18dbcd",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":30},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看基金净值/u13.png"}},
{
              "id":"1f84d4b21ecd4e928d47a25e8cb8ad31",
              "label":"",
              "type":"tableCell",
              "styleType":"tableCell",
              "visible":true,
              "style":{
                "horizontalAlignment":"center",
                "verticalAlignment":"middle",
                "location":{
                  "x":200,
                  "y":60},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"54ff96bf39de4bd3a638f43400db1788",
                  "label":"",
                  "isContained":true,
                  "type":"richTextPanel",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "horizontalAlignment":"center",
                    "verticalAlignment":"middle",
                    "location":{
                      "x":200,
                      "y":60},
                    "size":{
                      "width":100,
                      "height":30}},
                  "adaptiveStyles":{
}}],
              "images":{
                "normal~":"images/查看基金净值/u25.png"}}]},
{
          "id":"7d6d447b86c2474a875053401005aeca",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":636,
              "y":374},
            "size":{
              "width":522,
              "height":152}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a60545c757f847a2ac3d4a8d76cf5e4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":636,
                  "y":374},
                "size":{
                  "width":522,
                  "height":152}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03fdace9ab604736be67e3428519552d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"24px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":130,
              "y":12},
            "size":{
              "width":400,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"104c978646084bfab9c2061c2da4357d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"24px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":130,
                  "y":12},
                "size":{
                  "width":400,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"449285a95ea64366bfd4bc15bfabae13",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":130,
              "y":320},
            "size":{
              "width":140,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"537dd9f0ba1b40a8981f03c0acfe5ae3",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":310,
              "y":320},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ccd1a102aa9949ab843110720ac898f4",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":130,
              "y":675},
            "size":{
              "width":140,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2e573373bdbb4cf6b4a5b877b946a6fa",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":310,
              "y":675},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "8647ad65ff0e409ea9d43ed9e6fbd1e4":{
      "scriptId":"u0"},
    "143ebd4e802e475bafd5f7c7e43d064b":{
      "scriptId":"u1"},
    "33b7374af81b4f2c95c4c41e26135e90":{
      "scriptId":"u2"},
    "f9e24f8c413248448af9fbb1ffb53b64":{
      "scriptId":"u3"},
    "3674615cae054fbfb721242bd78e0412":{
      "scriptId":"u4"},
    "7676c4ab66044f72ad2a3c6849841c1e":{
      "scriptId":"u5"},
    "cbf44fdaa7cf47dc97f3b3cbbb036983":{
      "scriptId":"u6"},
    "0bc4bf5529ff47eaa66c383ad4fa5312":{
      "scriptId":"u7"},
    "ee008f00753340b59e53827fe7a84d46":{
      "scriptId":"u8"},
    "e51b8eeccf834a76b918ab5142809515":{
      "scriptId":"u9"},
    "c17ca8bdbbd04ebbae7c65c9f140574d":{
      "scriptId":"u10"},
    "ddf01e81d5c14ea78e7b8e283dd73a6e":{
      "scriptId":"u11"},
    "dfdf9cf8ccf0427ea1c4e4b8db276cbf":{
      "scriptId":"u12"},
    "9758c331a4d74006bd2b6e3cff60e2fb":{
      "scriptId":"u13"},
    "6952e97a4a704acda7b5c33dcb7921b2":{
      "scriptId":"u14"},
    "e1a46afc28b144b681f79dc50448dcc2":{
      "scriptId":"u15"},
    "de154c332c5a4ce08711ed78f79bc259":{
      "scriptId":"u16"},
    "4e0701002e4948858c4431ca866e7642":{
      "scriptId":"u17"},
    "e1d5d8fffdb5402d9d2eb7845d51c19c":{
      "scriptId":"u18"},
    "f3ed505831d24ab090cd959ceca37f9b":{
      "scriptId":"u19"},
    "89c7ed01634a44e093ff8a448d18dbcd":{
      "scriptId":"u20"},
    "3ffe1c2ecdaa44dd99815a6984ef7de3":{
      "scriptId":"u21"},
    "4e7f393ece6241ce918a98bf7a3f9e36":{
      "scriptId":"u22"},
    "0dc8247259f847ca8d8be764ab4b7427":{
      "scriptId":"u23"},
    "8ba3ca9545dc4733ba23e9e2fc0dcb6b":{
      "scriptId":"u24"},
    "1f84d4b21ecd4e928d47a25e8cb8ad31":{
      "scriptId":"u25"},
    "54ff96bf39de4bd3a638f43400db1788":{
      "scriptId":"u26"},
    "7d6d447b86c2474a875053401005aeca":{
      "scriptId":"u27"},
    "a60545c757f847a2ac3d4a8d76cf5e4e":{
      "scriptId":"u28"},
    "03fdace9ab604736be67e3428519552d":{
      "scriptId":"u29"},
    "104c978646084bfab9c2061c2da4357d":{
      "scriptId":"u30"},
    "449285a95ea64366bfd4bc15bfabae13":{
      "scriptId":"u31"},
    "537dd9f0ba1b40a8981f03c0acfe5ae3":{
      "scriptId":"u32"},
    "ccd1a102aa9949ab843110720ac898f4":{
      "scriptId":"u33"},
    "2e573373bdbb4cf6b4a5b877b946a6fa":{
      "scriptId":"u34"}}});