$axure.loadCurrentPage({
  "url":"选择沟通方式、留言.html",
  "generationDate":new Date(1660118457847.93),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"712fbabc1cca4869b562aea130d71361",
    "type":"Axure:Page",
    "name":"选择沟通方式、留言",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"84737ba05a70465d87a3df9a99c7281e",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":30,
              "y":0},
            "size":{
              "width":230,
              "height":420}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ed48e339fcd4d5c8fc4fc989fd2a232",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":30,
                  "y":0},
                "size":{
                  "width":230,
                  "height":420}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择沟通方式、留言/u0.png"}},
{
          "id":"65389544b55a4c7d89871ca7b5329e09",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":68,
              "y":70},
            "size":{
              "width":154,
              "height":347}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10a554cd8ee54ddeab0669ed9f7a59bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":68,
                  "y":70},
                "size":{
                  "width":154,
                  "height":347}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择沟通方式、留言/u2.png"}},
{
          "id":"a9d9d2a2eab74375a694744927a759d5",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":615,
              "y":30},
            "size":{
              "width":370,
              "height":260}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e566bab99b8746fba712746c9f756b49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":615,
                  "y":30},
                "size":{
                  "width":370,
                  "height":260}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择沟通方式、留言/u4.png"}},
{
          "id":"86e6821bddbf458ab3cc08c57f730cfc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":645,
              "y":60},
            "size":{
              "width":40,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fa0c139c9a9340e98fad5859a6f38ece",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":645,
                  "y":60},
                "size":{
                  "width":40,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择沟通方式、留言/u6.png"}},
{
          "id":"b301eb47d02d42249a987559832478dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":695,
              "y":60},
            "size":{
              "width":6,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ca5be3ebc4f4811a51ec5a49c8800de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":695,
                  "y":60},
                "size":{
                  "width":6,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a91370be822849e8af6f5c7c3ee6a70e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":286,
              "y":460},
            "size":{
              "width":545,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dde13fdd1fc4748beb609b7bfb73f5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":286,
                  "y":460},
                "size":{
                  "width":545,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e9129b0ca3244ad59bdda0f3e78723e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":695,
              "y":60},
            "size":{
              "width":200,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d743ab655114f5ca3b6baf20eb9743d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":695,
                  "y":60},
                "size":{
                  "width":200,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择沟通方式、留言/u12.png"}},
{
          "id":"c4391521abf3415eae10cd5600b0d2d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":711,
              "y":72},
            "size":{
              "width":126,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76e1e66c3a2e47e0b2323fb7e21201e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":711,
                  "y":72},
                "size":{
                  "width":126,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e42fc9e38043451cbee172e0c17d731c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":711,
              "y":102},
            "size":{
              "width":84,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7545846ab995496d9911c02986d112c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":711,
                  "y":102},
                "size":{
                  "width":84,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"790f872f38914e129fe102d0c3a4c821",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":711,
              "y":128},
            "size":{
              "width":54,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb0d0e7a8af54890b86a347dc6d4627f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":711,
                  "y":128},
                "size":{
                  "width":54,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7a89ae8ef30e4819a85d9e9ef143f723",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":711,
              "y":152},
            "size":{
              "width":146,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab8c8676039e4a629e5f1f12dd97ccbe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":711,
                  "y":152},
                "size":{
                  "width":146,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8c80c6e9e7544855a71008096ea4dc87",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":40},
            "size":{
              "width":270,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2312b95b33fc48aa8a5305da5a3040dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":40},
                "size":{
                  "width":270,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择沟通方式、留言/u22.png"}},
{
          "id":"ccb2ed9b9cfd43d28f8454fb385cca19",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":307,
              "y":60},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6b39e3195ab4a109e01009d9c609a17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":307,
                  "y":60},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1a345e20c60433d80255f37fc286b53",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":358,
              "y":60},
            "size":{
              "width":162,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"61bb22dd33b64d5aacbc0c863aa6c5a5",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":369,
              "y":115},
            "size":{
              "width":151,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"34cb7b41b172408b9ae5a818db239b27",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":307,
              "y":115},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1b5238acb4d4499bc403f5b48e1d553",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":307,
                  "y":115},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"de84e43520594aa5b5953beddbf53679",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":350,
              "y":155},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"1113bea3c0874cb9974e605ea2eab583",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":307,
              "y":87},
            "size":{
              "width":41,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"960741ff8f1c4379a1f0837154dfa670",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":307,
                  "y":87},
                "size":{
                  "width":41,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92879a9f88874eda83e8e01740e3c205",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":358,
              "y":87},
            "size":{
              "width":162,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"86e8c96a8973432eb7d1f0b0ebfcc4a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":20},
            "size":{
              "width":200,
              "height":48}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e21d4fde405468cb4bab9a1cc8fa559",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":20},
                "size":{
                  "width":200,
                  "height":48}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fe140759bbb64ef8ae6d264f84b429e2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":280,
              "y":508},
            "size":{
              "width":449,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61bfeb0f44564615a31475f2de1e4653",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":280,
                  "y":508},
                "size":{
                  "width":449,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "84737ba05a70465d87a3df9a99c7281e":{
      "scriptId":"u0"},
    "5ed48e339fcd4d5c8fc4fc989fd2a232":{
      "scriptId":"u1"},
    "65389544b55a4c7d89871ca7b5329e09":{
      "scriptId":"u2"},
    "10a554cd8ee54ddeab0669ed9f7a59bc":{
      "scriptId":"u3"},
    "a9d9d2a2eab74375a694744927a759d5":{
      "scriptId":"u4"},
    "e566bab99b8746fba712746c9f756b49":{
      "scriptId":"u5"},
    "86e6821bddbf458ab3cc08c57f730cfc":{
      "scriptId":"u6"},
    "fa0c139c9a9340e98fad5859a6f38ece":{
      "scriptId":"u7"},
    "b301eb47d02d42249a987559832478dd":{
      "scriptId":"u8"},
    "3ca5be3ebc4f4811a51ec5a49c8800de":{
      "scriptId":"u9"},
    "a91370be822849e8af6f5c7c3ee6a70e":{
      "scriptId":"u10"},
    "1dde13fdd1fc4748beb609b7bfb73f5b":{
      "scriptId":"u11"},
    "e9129b0ca3244ad59bdda0f3e78723e1":{
      "scriptId":"u12"},
    "6d743ab655114f5ca3b6baf20eb9743d":{
      "scriptId":"u13"},
    "c4391521abf3415eae10cd5600b0d2d5":{
      "scriptId":"u14"},
    "76e1e66c3a2e47e0b2323fb7e21201e5":{
      "scriptId":"u15"},
    "e42fc9e38043451cbee172e0c17d731c":{
      "scriptId":"u16"},
    "7545846ab995496d9911c02986d112c7":{
      "scriptId":"u17"},
    "790f872f38914e129fe102d0c3a4c821":{
      "scriptId":"u18"},
    "eb0d0e7a8af54890b86a347dc6d4627f":{
      "scriptId":"u19"},
    "7a89ae8ef30e4819a85d9e9ef143f723":{
      "scriptId":"u20"},
    "ab8c8676039e4a629e5f1f12dd97ccbe":{
      "scriptId":"u21"},
    "8c80c6e9e7544855a71008096ea4dc87":{
      "scriptId":"u22"},
    "2312b95b33fc48aa8a5305da5a3040dc":{
      "scriptId":"u23"},
    "ccb2ed9b9cfd43d28f8454fb385cca19":{
      "scriptId":"u24"},
    "b6b39e3195ab4a109e01009d9c609a17":{
      "scriptId":"u25"},
    "a1a345e20c60433d80255f37fc286b53":{
      "scriptId":"u26"},
    "61bb22dd33b64d5aacbc0c863aa6c5a5":{
      "scriptId":"u27"},
    "34cb7b41b172408b9ae5a818db239b27":{
      "scriptId":"u28"},
    "e1b5238acb4d4499bc403f5b48e1d553":{
      "scriptId":"u29"},
    "de84e43520594aa5b5953beddbf53679":{
      "scriptId":"u30"},
    "1113bea3c0874cb9974e605ea2eab583":{
      "scriptId":"u31"},
    "960741ff8f1c4379a1f0837154dfa670":{
      "scriptId":"u32"},
    "92879a9f88874eda83e8e01740e3c205":{
      "scriptId":"u33"},
    "86e8c96a8973432eb7d1f0b0ebfcc4a5":{
      "scriptId":"u34"},
    "9e21d4fde405468cb4bab9a1cc8fa559":{
      "scriptId":"u35"},
    "fe140759bbb64ef8ae6d264f84b429e2":{
      "scriptId":"u36"},
    "61bfeb0f44564615a31475f2de1e4653":{
      "scriptId":"u37"}}});