$axure.loadCurrentPage({
  "url":"转发.html",
  "generationDate":new Date(1659921932136.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"efbd1049188142b9813e2a8d22d3c918",
    "type":"Axure:Page",
    "name":"转发",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b97f005e2e734df88a481e284891ffd7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":39,
              "y":13},
            "size":{
              "width":1111,
              "height":507}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5225555e9aad4f719d278e680296837c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":39,
                  "y":13},
                "size":{
                  "width":1111,
                  "height":507}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转发/u0.jpg"}},
{
          "id":"cf67d2c04ce946e48fd4d53f44b4e3e7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":90,
              "y":612},
            "size":{
              "width":498,
              "height":438}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0fd82e5b3edf4094baf5acd265a96bd6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":90,
                  "y":612},
                "size":{
                  "width":498,
                  "height":438}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转发/u2.jpg"}},
{
          "id":"fcecf4bbbe68441086f8c1d9f1e24f60",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":350},
            "size":{
              "width":180,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57c4d005f0284b86aa955d471022101f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":350},
                "size":{
                  "width":180,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转发/u4.png"}},
{
          "id":"0d5a337b4d024fb9afb1bd36fa088c4f",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":850,
              "y":310},
            "size":{
              "width":110,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d33e5c70563440ddb6dc9dbed922af6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":850,
                  "y":310},
                "size":{
                  "width":110,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转发/u6.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "b97f005e2e734df88a481e284891ffd7":{
      "scriptId":"u0"},
    "5225555e9aad4f719d278e680296837c":{
      "scriptId":"u1"},
    "cf67d2c04ce946e48fd4d53f44b4e3e7":{
      "scriptId":"u2"},
    "0fd82e5b3edf4094baf5acd265a96bd6":{
      "scriptId":"u3"},
    "fcecf4bbbe68441086f8c1d9f1e24f60":{
      "scriptId":"u4"},
    "57c4d005f0284b86aa955d471022101f":{
      "scriptId":"u5"},
    "0d5a337b4d024fb9afb1bd36fa088c4f":{
      "scriptId":"u6"},
    "d33e5c70563440ddb6dc9dbed922af6c":{
      "scriptId":"u7"}}});