$axure.loadCurrentPage({
  "url":"产品留言.html",
  "generationDate":new Date(1660102156444.6),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"754e1ee4a1e24ecc833e31f4c77fd9db",
    "type":"Axure:Page",
    "name":"产品留言",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"488a09dfe7a4454181f22a0e87edc111",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":90},
            "size":{
              "width":621,
              "height":1170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16f788d1d6644bfbbadb20dbbabdadba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":90},
                "size":{
                  "width":621,
                  "height":1170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/产品留言/u0.png"}},
{
          "id":"962d262fba594847898183bf471a80ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":32},
            "size":{
              "width":545,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8bfa884ca804bc297e769c3c12a698d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":150,
                  "y":32},
                "size":{
                  "width":545,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "488a09dfe7a4454181f22a0e87edc111":{
      "scriptId":"u0"},
    "16f788d1d6644bfbbadb20dbbabdadba":{
      "scriptId":"u1"},
    "962d262fba594847898183bf471a80ad":{
      "scriptId":"u2"},
    "a8bfa884ca804bc297e769c3c12a698d":{
      "scriptId":"u3"}}});