$axure.loadCurrentPage({
  "url":"搜索.html",
  "generationDate":new Date(1660126800080.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8ffbc4c96a0f43d8b1c09ca91b84f0e8",
    "type":"Axure:Page",
    "name":"搜索",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7e5b2346d083495a8b3b6c3368fdab5f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":59,
              "y":10},
            "size":{
              "width":621,
              "height":1170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"702d627d9d114b07896698a347f74ece",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":59,
                  "y":10},
                "size":{
                  "width":621,
                  "height":1170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u0.jpg"}},
{
          "id":"f9f20f2cc8dd42dfa0ec7ad39ede596b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":710,
              "y":20},
            "size":{
              "width":621,
              "height":1170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dfa516957d84c82b0fcdf144313880a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":710,
                  "y":20},
                "size":{
                  "width":621,
                  "height":1170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/搜索/u2.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "7e5b2346d083495a8b3b6c3368fdab5f":{
      "scriptId":"u0"},
    "702d627d9d114b07896698a347f74ece":{
      "scriptId":"u1"},
    "f9f20f2cc8dd42dfa0ec7ad39ede596b":{
      "scriptId":"u2"},
    "3dfa516957d84c82b0fcdf144313880a":{
      "scriptId":"u3"}}});